// Design: Modern Button Component Library
// Generated by OwnFlow Figma Agent for Figma Scripter
// This code creates a reusable button component system with multiple variants

async function createDesign() {
  const page = figma.currentPage;

  // Create a frame to hold all button variants
  const container = figma.createFrame();
  container.name = "Button Library";
  container.resize(600, 400);
  container.fills = [{type: "SOLID", color: {r: 0.95, g: 0.95, b: 0.95}}];
  container.layoutMode = "VERTICAL";
  container.itemSpacing = 32;
  container.paddingLeft = 24;
  container.paddingRight = 24;
  container.paddingTop = 24;
  container.paddingBottom = 24;

  // ── Default Button Component ────────────────────────────────────────────
  const defaultButton = figma.createComponent();
  defaultButton.name = "Button";
  defaultButton.resize(120, 48);
  defaultButton.layoutMode = "HORIZONTAL";
  defaultButton.itemSpacing = 8;
  defaultButton.paddingLeft = 16;
  defaultButton.paddingRight = 16;

  // Add background to default button
  const defaultBg = figma.createRectangle();
  defaultBg.name = "Background";
  defaultBg.resize(120, 48);
  defaultBg.fills = [{type: "SOLID", color: {r: 0.2, g: 0.4, b: 1}}];
  defaultBg.cornerRadius = 6;
  defaultButton.appendChild(defaultBg);
  defaultBg.moveToBack();

  // Add text to default button
  const defaultText = figma.createText();
  const defaultTextFont = {family: "Inter", style: "Semi Bold"};
  await figma.loadFontAsync(defaultTextFont);
  defaultText.name = "Label";
  defaultText.characters = "Click me";
  defaultText.fontSize = 16;
  defaultText.fontName = defaultTextFont;
  defaultText.fills = [{type: "SOLID", color: {r: 1, g: 1, b: 1}}];
  defaultButton.appendChild(defaultText);

  // ── Hover State Button Component ────────────────────────────────────────
  const hoverButton = defaultButton.clone();
  hoverButton.name = "Button/Hover";

  // Update hover button background color
  const hoverBg = hoverButton.children[0];
  hoverBg.fills = [{type: "SOLID", color: {r: 0.15, g: 0.3, b: 0.85}}];

  // ── Active State Button Component ───────────────────────────────────────
  const activeButton = defaultButton.clone();
  activeButton.name = "Button/Active";

  // Update active button background color
  const activeBg = activeButton.children[0];
  activeBg.fills = [{type: "SOLID", color: {r: 0.1, g: 0.2, b: 0.7}}];

  // ── Disabled State Button Component ─────────────────────────────────────
  const disabledButton = defaultButton.clone();
  disabledButton.name = "Button/Disabled";
  disabledButton.opacity = 0.5;

  // Update disabled button background color
  const disabledBg = disabledButton.children[0];
  disabledBg.fills = [{type: "SOLID", color: {r: 0.8, g: 0.8, b: 0.8}}];

  // ── Secondary Button Component ──────────────────────────────────────────
  const secondaryButton = defaultButton.clone();
  secondaryButton.name = "Button/Secondary";

  // Update secondary button background color
  const secondaryBg = secondaryButton.children[0];
  secondaryBg.fills = [{type: "SOLID", color: {r: 0.95, g: 0.95, b: 0.95}}];
  secondaryBg.strokes = [{type: "SOLID", color: {r: 0.2, g: 0.4, b: 1}}];
  secondaryBg.strokeWeight = 2;

  // Update secondary button text color
  const secondaryText = secondaryButton.children[1];
  secondaryText.fills = [{type: "SOLID", color: {r: 0.2, g: 0.4, b: 1}}];

  // ── Create a variants frame ─────────────────────────────────────────────
  const variantsFrame = figma.createFrame();
  variantsFrame.name = "Button Variants";
  variantsFrame.resize(600, 300);
  variantsFrame.layoutMode = "VERTICAL";
  variantsFrame.itemSpacing = 16;
  variantsFrame.paddingLeft = 16;
  variantsFrame.paddingTop = 16;

  // Add labels and variants
  const variants = [
    { component: defaultButton, label: "Default (size: 120x48)" },
    { component: hoverButton, label: "Hover (darker shade)" },
    { component: activeButton, label: "Active (darker shade)" },
    { component: disabledButton, label: "Disabled (50% opacity)" },
    { component: secondaryButton, label: "Secondary (outline style)" },
  ];

  for (const variant of variants) {
    // Create a row frame for each variant
    const row = figma.createFrame();
    row.name = `Row: ${variant.label}`;
    row.resize(560, 60);
    row.layoutMode = "HORIZONTAL";
    row.itemSpacing = 16;
    row.paddingLeft = 12;
    row.paddingTop = 6;
    row.paddingBottom = 6;
    row.fills = [{type: "SOLID", color: {r: 1, g: 1, b: 1}}];

    // Create label text
    const labelText = figma.createText();
    labelText.name = "Variant Label";
    labelText.characters = variant.label;
    labelText.fontSize = 13;
    labelText.fills = [{type: "SOLID", color: {r: 0.4, g: 0.4, b: 0.4}}];
    row.appendChild(labelText);

    // Add a clone of the button variant
    const buttonClone = variant.component.clone();
    buttonClone.name = "Preview";
    row.appendChild(buttonClone);

    variantsFrame.appendChild(row);
  }

  // Add container to page
  container.appendChild(defaultButton);
  container.appendChild(hoverButton);
  container.appendChild(activeButton);
  container.appendChild(disabledButton);
  container.appendChild(secondaryButton);

  page.insertChild(0, container);
  page.insertChild(1, variantsFrame);

  // Select the main container to show the user what was created
  figma.currentPage.selection = [container];
}

// Execute the design generation
createDesign().catch(e => {
  console.error("Design generation failed:", e);
});

